### ISSUE TITLE
Options expire attribute should be integer

### ISSUE THREAD

**Issue by Aless55** [XRPL-Labs/XUMM-SDK-PHP#16]
At the moment the `expire` attribute of the `Options` class is `bool`.

It is mentioned here: https://xumm.readme.io/docs/doc-payload-life-cycle#2-compose-payload-options that the expire attribute is an `int32`, the datatype should therefore be changed to `int`.

**Comment by paulinevos** [comment]
Thanks for catching this one as well, about to merge and release
