### ISSUE TITLE
Some 'SField' fields were renamed in rippled v1.9.0

### ISSUE THREAD

**Issue by Aless55** [XRPL-Labs/XUMM-SDK-PHP#21]
I cannot submit a payload for a `NFTokenMint` transaction anymore if I set the `NFTokenTaxon` field instead of the `TokenTaxon` field. 
At the moment everything works fine if I set `TokenTaxon` instead of `NFTokenTaxon`. My temporary fix is sending both, in case the API changes.

You can find all renamed `SField` fields here: https://xrpl.org/blog/2022/rippled-1.9.0.html (somewhere in the middle of the page)
There also some other interesting changes like `NonFungibleToken -> NFToken` etc.

====Edit
Same problem with `TokenID` and `NFTokenID` in the `NFTokenCreateOffer` transaction.

**Comment by WietseWind** [comment]
Thanks. We are aware, indeed. This is actually not related to the PHP (or any SDK language's) implementation but to the XUMM API (called by the SDKs) in general: it has not been updated yet, as we're waiting for rippled 1.9.0 fixes (1.9.0 contains flaws and has been removed from the `unstable` release channel). It's a work in progress.
