### ISSUE TITLE
"hex" field missing in GetPayload Response

### ISSUE THREAD

**Issue by Aless55** [XRPL-Labs/XUMM-SDK-PHP#22]
The `GetPayload` `Response` is currently not returning the signed transaction blob which would be found in the `Response->hex` field.

**Comment by WietseWind** [comment]
Thanks for the heads up! Do you have a payload UUID for me to check :)?

**Comment by Aless55** [comment]
I am sorry it was a bit late, I think I misdescribed the problem, the API is returning the `hex` field correctly. But the Response Object that is serialized is lacking it. Should be a quick fix in adding the parameter, I will create a pull request.

**Comment by WietseWind** [comment]
Clear, noticed the PR as well. Thank you!!

**Comment by paulinevos** [comment]
Merged and fixed :)
