### ISSUE TITLE
Add missing getNftokenDetail() method

### ISSUE THREAD

**Issue by zgrguric** [XRPL-Labs/XUMM-SDK-PHP#34]
This method was introduced with v1.0 xumm sdk.
[https://docs.xumm.dev/js-ts-sdk/sdk-syntax/xumm.helpers-.../getnftokendetail-...](https://docs.xumm.dev/js-ts-sdk/sdk-syntax/xumm.helpers-.../getnftokendetail-...)

This might require adding jwtflow context. If this was not intended as endpoint for using outside user context, then close this issue.

**Comment by WietseWind** [comment]
JWT is out of scope, PHP = backend = API key + secret. JWT is useful for frontend things, and so the JWT endpoints are only part of the TS/JS SDK :)
